### PR TITLE
[Feature][Flink] Uniform parameters with Doris Connector 

### PR DESCRIPTION
**Pull request by JNSimba**
## Purpose of this pull request

Uniform parameters with Doris Connector 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] Change does not need document change, or I will submit document change to https://github.com/InterestingLab/seatunnel-docs later

### CODE REVIEW

**Comment by CalvinKirs** [comment]
Thank you for your contribution, @xtr1993  has submitted a version, can you update the code to see if it can be consistent.

**Comment by JNSimba** [comment]
> Thank you for your contribution, @xtr1993 has submitted a version, can you update the code to see if it can be consistent.

ok，i will check

**Comment by JNSimba** [comment]
Distinguish between flink and spark documents and unify parameters

**Comment by JNSimba** [comment]
@CalvinKirs Hello, I resolved the conflict, and after discussing with @xtr1993 classmates, I unified the submission parameters of flink, please review

**Review by CalvinKirs — APPROVED** [review]
LGTM
Looking forward to your next contribution：）

**Pull request merged**
