### PR TITLE
[SeaTunnel#1021] make maven-shade-plugin only applied to core modules

### LINKED ISSUE #1021: [Feature][core] make maven-shade-plugin only applied to core modules
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently maven-shade-plugin is effect all modules in the project because  it was add in parent pom, in fact It only needed by core-spark and core-flink modules to package in plugins.
So I put the maven-shade-plugin to core modules only, and this optimize can reduce build time(mvn clean package -DskipTests) from 10m to 6m, which helps #814.

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yx91490**
## Purpose of this pull request

close #1021 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
@leo65535 PTAL,Thx

**Comment by an-shi-chi-fan** [comment]
SGTM

**Comment by leo65535** [comment]
hi @yx91490, `seatunnel-core-sql` also need `maven-shade-plugin`, thanks

**Comment by leo65535** [comment]
em.. it seems will cause bug, `transforms` `connectors` only contain itself.

```
[dcadmin@dcadmin seatunnel-connectors]$ du -chs *
4.0K    pom.xml
1.5M    seatunnel-connector-flink-console
1.8M    seatunnel-connector-flink-doris
1.8M    seatunnel-connector-flink-druid
1.6M    seatunnel-connector-flink-elasticsearch
1.5M    seatunnel-connector-flink-fake
2.0M    seatunnel-connector-flink-file
1.6M    seatunnel-connector-flink-jdbc
1.6M    seatunnel-connector-flink-kafka
1.5M    seatunnel-connector-flink-socket
1.7M    seatunnel-connector-spark-clickhouse
1.5M    seatunnel-connector-spark-console
1.7M    seatunnel-connector-spark-doris
1.6M    seatunnel-connector-spark-elasticsearch
2.5M    seatunnel-connector-spark-email
1.6M    seatunnel-connector-spark-fake
1.7M    seatunnel-connector-spark-file
1.6M    seatunnel-connector-spark-hbase
1.6M    seatunnel-connector-spark-hive
1.6M    seatunnel-connector-spark-hudi
3.2M    seatunnel-connector-spark-jdbc
1.8M    seatunnel-connector-spark-kafka
1.6M    seatunnel-connector-spark-kudu
1.5M    seatunnel-connector-spark-mongodb
2.2M    seatunnel-connector-spark-phoenix
1.8M    seatunnel-connector-spark-redis
1.5M    seatunnel-connector-spark-socket
```

### Missing dependency
image

**Comment by yx91490** [comment]
> em.. it seems will cause bug, `transforms` `connectors` only contain itself.
> 
> ```
> [dcadmin@dcadmin seatunnel-connectors]$ du -chs *
> 4.0K    pom.xml
> 1.5M    seatunnel-connector-flink-console
> 1.8M    seatunnel-connector-flink-doris
> 1.8M    seatunnel-connector-flink-druid
> 1.6M    seatunnel-connector-flink-elasticsearch
> 1.5M    seatunnel-connector-flink-fake
> 2.0M    seatunnel-connector-flink-file
> 1.6M    seatunnel-connector-flink-jdbc
> 1.6M    seatunnel-connector-flink-kafka
> 1.5M    seatunnel-connector-flink-socket
> 1.7M    seatunnel-connector-spark-clickhouse
> 1.5M    seatunnel-connector-spark-console
> ```
> 
> ### Missing dependencies
> image

Currently, it seems that plugins no need to package dependencies, they will be all packaged to a single jar by maven-shade-plugin finally.

**Comment by xleoken** [comment]
hi @yx91490, let's imagine a scenario, if flink-console and flink-doris module references the same dependency called `log-xx` dependency, flink-console requires `log-xx.1.2.0`, but flink-doris requires `log-xx.1.5.0`. In this scenario, we need the shade plugin.
BTW, seatunnel has many connectors, maven-shade-plugin is useful for each module when meets conflict.

```
[dcadmin@dcadmin seatunnel-connectors]$ du -chs *
4.0K    pom.xml
1.5M    seatunnel-connector-flink-console
1.8M    seatunnel-connector-flink-doris
```

**Comment by yx91490** [comment]
> hi @yx91490, let's imagine a scenario, if flink-console and flink-doris module references the same dependency called `log-xx` dependency, flink-console requires `log-xx.1.2.0`, but flink-doris requires `log-xx.1.5.0`. In this scenario, we need the shade plugin. BTW, seatunnel has many connectors, maven-shade-plugin is useful for each module when meets conflict.
> 
> ```
> [dcadmin@dcadmin seatunnel-connectors]$ du -chs *
> 4.0K    pom.xml
> 1.5M    seatunnel-connector-flink-console
> 1.8M    seatunnel-connector-flink-doris
> ```

make sense, but in this scenario you should configure maven-shade-plugin with `relocations`, but currently no plugin module configured `relocations`, that is , currently maven-shade-plugin only used to package to a single jar, no other effects.

**Comment by xleoken** [comment]
You are quite right. It seems not necessary to make the change currently.

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
