### PR TITLE
[SeaTunnel #856][community] Migrate organization from interestinglab to apache

### PR DESCRIPTION
**Pull request by zhongjiajie**
close: #856

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason: Only keyword changed
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by zhongjiajie** [comment]
@CalvinKirs I find out our document is still held in https://interestinglab.github.io/ instead of apache domain, so I do not change this link. Do we have a plan to migrate it?

**Comment by wuchunfu** [comment]
> @CalvinKirs I find out our document is still held in https://interestinglab.github.io/ instead of apache domain, so I do not change the link like that. Do we have a plan to migrate it?

@CalvinKirs  I think we'd better complete the document migration work as soon as possible, because we have officially announced it to the public, I think I can do this work, please feel free to call me if you need to.

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
> > @CalvinKirs I find out our document is still held in https://interestinglab.github.io/ instead of apache domain, so I do not change the link like that. Do we have a plan to migrate it?
> 
> @CalvinKirs I think we'd better complete the document migration work as soon as possible, because we have officially announced it to the public, I think I can do this work, please feel free to call me if you need to.

I left a review in the #808, and I will complete the #808 review as soon as possible.

**Pull request merged**
