### PR TITLE
[SeaTunnel#1023]Revert "[hotfix] remove plugins folder"

### LINKED ISSUE #1023: [Bug] [startup script] lost plugins directory cause start script error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

startup script show error plugins directory not found

### SeaTunnel Version

2.0.5

### SeaTunnel Config

```conf
No
```

### Running Command

```shell
general
```

### Error Exception

```log
plugins directory not found
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CalvinKirs**
Reverts apache/incubator-seatunnel#1009

this close #1023

### CODE REVIEW

**Comment by leo65535** [comment]
hi @CalvinKirs, `.gitkeep` and `seatunnel-demo.json` seems useless, we can remove them?

**Comment by CalvinKirs** [comment]
> hi @CalvinKirs, `.gitkeep` and `seatunnel-demo.json` seems useless, we can remove them?



> hi @CalvinKirs, `.gitkeep` and `seatunnel-demo.json` seems useless, we can remove them?

`.gitkeep` is for placeholders, since we can't commit empty folders.
`seatunnel-demo.json` seems to be for a simple example, can we keep it for now? What do you think

**Comment by leo65535** [comment]
> Hi, `.gitkeep` is for placeholders, since we can't commit empty folders.

Make sense, we can keep it, or we can put a `README.md` in this folder.

> `seatunnel-demo.json` seems to be for a simple example, can we keep it for now? What do you think?

We introduced a `seatunnel-example` module, so this file seems useless.

**Comment by CalvinKirs** [comment]
> > Hi, `.gitkeep` is for placeholders, since we can't commit empty folders.
> 
> Make sense, we can keep it, or we can put a `README.md` in this folder.
> 
> > `seatunnel-demo.json` seems to be for a simple example, can we keep it for now? What do you think?
> 
> We introduced a `seatunnel-example` module, so this file seems useless.



> > Hi, `.gitkeep` is for placeholders, since we can't commit empty folders.
> 
> Make sense, we can keep it, or we can put a `README.md` in this folder.
> 
> > `seatunnel-demo.json` seems to be for a simple example, can we keep it for now? What do you think?
> 
> We introduced a `seatunnel-example` module, so this file seems useless.

I suggest we keep it, it is necessary to keep an example here. This is where users need to care about configuration. If you don't keep it, you also need to submit a `.gitkeep`, we will use this path to parse the user's configuration file.

**Comment by leo65535** [comment]
> > > Hi, `.gitkeep` is for placeholders, since we can't commit empty folders.
> > 
> > 
> > Make sense, we can keep it, or we can put a `README.md` in this folder.
> > > `seatunnel-demo.json` seems to be for a simple example, can we keep it for now? What do you think?
> > 
> > 
> > We introduced a `seatunnel-example` module, so this file seems useless.
> 
> > > Hi, `.gitkeep` is for placeholders, since we can't commit empty folders.
> > 
> > 
> > Make sense, we can keep it, or we can put a `README.md` in this folder.
> > > `seatunnel-demo.json` seems to be for a simple example, can we keep it for now? What do you think?
> > 
> > 
> > We introduced a `seatunnel-example` module, so this file seems useless.
> 
> I suggest we keep it, it is necessary to keep an example here. This is where users need to care about configuration. If you don't keep it, you also need to submit a `.gitkeep`, we will use this path to parse the user's configuration file.

OK, let's keep it.

**Review by nielifeng — APPROVED** [review]
LGTM

**Pull request merged**
