### PR TITLE
[CI]Add codeQL action

### PR DESCRIPTION
**Pull request by CalvinKirs**

### CODE REVIEW

**Comment by leo65535** [comment]
hi @CalvinKirs, `codeQL` is new thing for me, what is its core function?

**Comment by CalvinKirs** [comment]
> hi @CalvinKirs, `codeQL` is new thing for me, what is its core function?

https://github.com/github/codeql-action

**Comment by CalvinKirs** [comment]
> > hi @CalvinKirs, `codeQL` is new thing for me, what is its core function?
> 
> https://github.com/github/codeql-action

@leo65535  hi, thank you for your attention. here are some introductions. What do you think?

**Comment by leo65535** [comment]
> here are some introductions

+1, this is a amusing feature which can help us scan the security issue.

**Comment by garyelephant** [comment]
@CalvinKirs ready to merge ? Why one of checks is failed ?

**Comment by CalvinKirs** [comment]
> @CalvinKirs ready to merge ? Why one of checks is failed ?

Not to merge for now, can you help determine this problem?

**Comment by CalvinKirs** [comment]
> > @CalvinKirs ready to merge ? Why one of checks is failed ?
> 
> Not to merge for now, can you help determine this problem?

https://github.com/apache/incubator-seatunnel/pull/881/files#annotation_2485781094

**Comment by CalvinKirs** [comment]
Sorry I can only resubmit the PR（#1033） since I deleted the branch.

**Pull request closed without merging**
