### PR TITLE
[Improvement][example]Use ${project.version} instead of deprecated ${parent.version}

### PR DESCRIPTION
**Pull request by JiangTChen**
## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by leo65535** [comment]
hi @JiangTChen, does any document describe `${parent.version}` is deprecated? thanks.

**Comment by JiangTChen** [comment]
> 



> hi @JiangTChen, does any document describe `${parent.version}` is deprecated? thanks.

Hi Leo, You can run `mvn clean`, then you will see below warning.

[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.apache.seatunnel:seatunnel-flink-examples:jar:2.0.5-SNAPSHOT
[WARNING] The expression ${parent.version} is deprecated. Please use ${project.parent.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by leo65535** [comment]
Hi @JiangTChen, mvn command output this message only `seatunnel-core-flink` module? What about the other modules?

**Comment by felix-thinkingdata** [comment]
> ${parent.version}

Yes, THERE is a version of Maven that says ${parent. Version} is a syntax error

**Comment by felix-thinkingdata** [comment]
> Hi @JiangTChen, mvn command output this message only `seatunnel-core-flink` module? What about the other modules?

Yes, THERE is a version of Maven that says ${parent. Version} is a syntax error

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by JiangTChen** [comment]
> 



> Hi @JiangTChen, mvn command output this message only `seatunnel-core-flink` module? What about the other modules?

Hi @leo65535 @felix-thinkingdata ,yes! only 'seatunnel-core-flink' has this problem. Other module is ${project.version}.
I pushed again with ${project.version}. please review.

**Review by leo65535 — APPROVED** [review]

**Pull request merged**
